version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Build phase complete
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r mygroupapp.zip .
artifacts:
  files:
    - mygroupapp.zip
